"""DB: Track table migration

Revision ID: 332bc5bdcb26
Revises: 59f30c363b4c
Create Date: 2025-04-26 15:38:52.994565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '332bc5bdcb26'
down_revision = '59f30c363b4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ipfs_cid', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_column('ipfs_cid')

    # ### end Alembic commands ###
