"""Migrate

Revision ID: 59f30c363b4c
Revises: 
Create Date: 2025-04-15 17:25:56.977524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59f30c363b4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sales_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wallet_address', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['wallet_address'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('wallet_address')

    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_column('sales_count')

    # ### end Alembic commands ###
