"""Added category

Revision ID: 688389957769
Revises: dea9e5a6ed3d
Create Date: 2025-04-10 18:08:23.695951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '688389957769'
down_revision = 'dea9e5a6ed3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track_perks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.Enum('exclusive', 'custom', 'stem', 'discord', 'instrumental', 'vocal', 'other', name='category'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track_perks', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
