"""Added: S3 url, and perk type within the DB

Revision ID: 96d2e77a4054
Revises: 9b228d1d6d69
Create Date: 2025-04-08 18:14:23.420723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96d2e77a4054'
down_revision = '9b228d1d6d69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track_perks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perk_type', sa.Enum('text', 'url', 'file', 'audio', name='perktype'), nullable=True))
        batch_op.add_column(sa.Column('s3_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track_perks', schema=None) as batch_op:
        batch_op.drop_column('s3_url')
        batch_op.drop_column('perk_type')

    # ### end Alembic commands ###
