"""Added: exclusive field to tracks

Revision ID: 9b228d1d6d69
Revises: e7449ff40a1a
Create Date: 2025-04-08 16:19:37.024411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b228d1d6d69'
down_revision = 'e7449ff40a1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exclusive', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_column('exclusive')

    # ### end Alembic commands ###
