"""Added fields for category

Revision ID: abf1f2e25b5a
Revises: 96d2e77a4054
Create Date: 2025-04-10 17:37:07.147534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abf1f2e25b5a'
down_revision = '96d2e77a4054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track_perks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.Enum('exclusive', 'custom', 'stem', 'instrumental', 'vocal', 'other', name='category'), nullable=True))
        batch_op.drop_column('url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track_perks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('category')

    # ### end Alembic commands ###
