"""dropped category

Revision ID: dea9e5a6ed3d
Revises: abf1f2e25b5a
Create Date: 2025-04-10 18:05:31.185705

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dea9e5a6ed3d'
down_revision = 'abf1f2e25b5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track_perks', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track_perks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', postgresql.ENUM('exclusive', 'custom', 'stem', 'instrumental', 'vocal', 'other', name='category'), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
