"""Added new fileds

Revision ID: e7449ff40a1a
Revises: f9e55cf6cd5e
Create Date: 2025-04-03 18:44:14.070542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7449ff40a1a'
down_revision = 'f9e55cf6cd5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Enum('pending', 'active', 'rejected', name='trackstatus'), nullable=True))
        batch_op.add_column(sa.Column('rejection_reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('status')
        batch_op.drop_column('approved')

    # ### end Alembic commands ###
